print("Bismillah")
print("Bismillah")
print("Bismillah")
print("Bismillah")
print("Bismillah")
print("Bismillah")
print("Bismillah")
print("Bismillah")
print("Bismillah")
print("Bismillah")
print("Bismillah")
print("Bismillah")
print("Bismillah")
print("Bismillah")
print("Bismillah")
print("Bismillah")
print("allah tera arab ha arab shukar")
print("Bismillah")
print("Bismillah")
print("Bismillah")
print("allah tera arab ha arab shukar")
